### ISSUE TITLE
More PSF options for simulated focal planes

### ISSUE THREAD

**Issue by NiallMac** [esheldon/galsim_extra#7]
This is perhaps too general for a single issue, but we can decide here how to split into several issues if necessary. Here are a couple of PSF options it would be nice to have:
i) Just read in and use PSFEx solutions from real DES images.
ii) Optical model from @cpdavis and @aaronroodman
iii) Combination of optical model and atmospheric component.

- (i) should be straightforward with the [des_psfex](http://galsim-developers.github.io/GalSim/classgalsim_1_1des_1_1des__psfex_1_1_d_e_s___p_s_f_ex.html) class in GalSim.
- (ii) and (iii) may be mostly interfacing with [Piff](https://github.com/rmjarvis/Piff) (@rmjarvis)?

**Comment by rmjarvis** [comment]
The first thing is already done.  cf. https://github.com/GalSim-developers/GalSim/blob/releases/1.4/examples/des/draw_psf.yaml

```
psf:
    type: DES_PSFEx

input :
    des_psfex :
        file_name : DECam_blah_psfcat.fits
        # And if you want the WCS to work out right, you also need this:
        image_file_name : DECam_blah.fits.fz
```

**Comment by rmjarvis** [comment]
The good optical model from Chris and Aaron would indeed be a nice module to have.

Not sure if we need something special for the third one.  I think the existing PowerSpectrum stuff works fine for the atmosphere.  e.g.
```
psf:
    type: Convolve
    items:
        - # optical component

            # Whatever the optical bit should be...

        - # atmospheric component
            type: Kolmogorov
            fwhm: # The mean fwhm across the whole focal plane
            ellip:
                type: PowerSpectrumShear
            magnify:
                type: PowerSpectrumMagnification

input:
    power_spectrum:
        index_key: exp_num
        # Heymans et al, 2012 found L0 ~= 3 arcmin, given as 180 arcsec here.
        e_power_function: '(k**2 + (1./180)**2)**(-11./6.)'
        b_power_function: '@input.power_spectrum.e_power_function'
        units: arcsec
        grid_spacing: 10  # arcsec -- should be smaller than scales of interest in rho1.
        # Here uses the focal_rmax value from FocalPlane output type.
        ngrid: '$math.ceil(2 * focal_rmax / @input.power_spectrum.grid_spacing)'
        center: 0,0
        variance: # choose some appropriate variance for <e_atm^2>
```
